services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      target: build
    command: bash -c "sleep 5 && bundle install && bundle exec rails db:prepare db:create db:migrate db:fixtures:load && bundle exec rails s -b 0.0.0.0 "
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/genshin_wiki_api_development

volumes:
  db-data: